language: node_js
node_js:
 - "12.18.3"
branches:
  only:
  - staging
  - master
deploy:
  - provider: elasticbeanstalk
    access_key_id: ${AWS_ACCESS_KEY_ID}
    secret_access_key:
      secure: ${AWS_SECRET_ACCESS_KEY}
    region: "eu-west-1"
    app: "nextjs-aws-app"
    env: "nextjs-aws-ap-staging"
    bucket_name: ${AWS_S3_BUCKET} 
    on:
      branch: "staging"

  - provider: elasticbeanstalk
    access_key_id: ${AWS_ACCESS_KEY_ID}
    secret_access_key:
      secure: ${AWS_SECRET_ACCESS_KEY}
    region: "eu-west-1"
    app: "next-app"                     
    env: "nextjs-aws-app-production"
    bucket_name: ${AWS_S3_BUCKET}
    on:
      branch: "master"

after_deploy:
  - echo "Application Deployed!"